# Generated by Django 6.0.2 on 2026-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=6)),
                ('cpassword', models.CharField(max_length=6)),
            ],
        ),
    ]
