# Generated by Django 6.0.2 on 2026-04-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
