# Generated by Django 6.0.2 on 2026-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
