# Generated by Django 6.0.2 on 2026-04-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_message_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='buyer', max_length=20),
        ),
    ]
