# Generated by Django 6.0.2 on 2026-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seller_email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
