# Generated by Django 6.0.2 on 2026-04-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_seller_email_alter_message_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seller_email',
        ),
    ]
